//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watermarked.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watermarked.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        internal static string AddFilesButton_Content {
            get {
                return ResourceManager.GetString("AddFilesButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        internal static string ClearListButton_Content {
            get {
                return ResourceManager.GetString("ClearListButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File List.
        /// </summary>
        internal static string FileListHeader {
            get {
                return ResourceManager.GetString("FileListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageWatermark_TabHeader {
            get {
                return ResourceManager.GetString("ImageWatermark_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select media files.
        /// </summary>
        internal static string OpenFilePicker_Title {
            get {
                return ResourceManager.GetString("OpenFilePicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to see a preview.
        /// </summary>
        internal static string Preview_SelectFile {
            get {
                return ResourceManager.GetString("Preview_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextWatermark_TabHeader {
            get {
                return ResourceManager.GetString("TextWatermark_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string WatermarkColor_Label {
            get {
                return ResourceManager.GetString("WatermarkColor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        internal static string WatermarkFontSize_Label {
            get {
                return ResourceManager.GetString("WatermarkFontSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Settings.
        /// </summary>
        internal static string WatermarkSettings_Header {
            get {
                return ResourceManager.GetString("WatermarkSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string WatermarkText_Label {
            get {
                return ResourceManager.GetString("WatermarkText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Text.
        /// </summary>
        internal static string WatermarkTextWrapping_Content {
            get {
                return ResourceManager.GetString("WatermarkTextWrapping_Content", resourceCulture);
            }
        }
    }
}
